### PR TITLE
Add decover effect

### PR DESCRIPTION
**Pull request by iojw**
Added a decover effect as mentioned in GCI

### CODE REVIEW

**Comment by Cervator** [comment]
Cool, neat effect :-) I wonder what @xrtariq2594 had in mind when he named it though. What's "Decover" meant to mean? Is that a spell or effect in some other game I just haven't played?

May we should indeed come up with some little command to programmatically apply a Component to a player for easy testing.

**Comment by iojw** [comment]
I think it's supposed to be the opposite of Recover haha - I haven't seen it before either

I think I could add a console command for adding and removing effects but from what I understand, for a generic console command we would need a method which can retreive Components by name. Hmm, maybe something with ComponentLibrary?

**Comment by rzats** [comment]
@Cervator: it's generally covered by "fire" or sometimes "arcane"-type abilities that suppress health regeneration in regenerating enemies among other things. If this effect gets a visual representation I'd go for a dark red slow-burning flame.

**Comment by xrtariq2594** [comment]
Good work @iojw!

@Cervator I took the Decover name from [this TVTropes article](http://tvtropes.org/pmwiki/pmwiki.php/Main/StandardStatusEffects). It basically prevents healing to the afflicted entity. It doesn't prevent curing status ailments though.

@iojw If you want to add that console command, go right ahead. It'd really useful for testing future effects. When you feel you're done, let us know and I can accept your contribution. Right now, it fulfilled the specs required.

**Comment by xrtariq2594** [comment]
Good work @iojw!

If you have any new ideas for alteration effects, please let us know.

**Comment by iojw** [comment]
@Cervator: I've added some javadoc comments for the effect. I'm not very familiar with how to write them so do take a look and let me know if they are alright.

@xrtariq2594: Thanks 😄 I looked into implementing a command for arbitrary effects but the code came up to be really ugly and hacky. I'll try to work on it further. Maybe a command for components in general as mentioned would be better for all modules.

**Pull request merged**
