### PR TITLE
Added stun effect

### PR DESCRIPTION
**Pull request by iojw**
Hi, do let me know if there are any problems with this implementation. I haven't managed to claim the task on GCI as my parental consent form is still awaiting approval, but I started working on this as it seemed quite interesting :-) I will claim the task once I can. Thank you!

### CODE REVIEW

**Comment by xrtariq2594** [comment]
Alright, I looked through your implementation @iojw. It looks good. Though, I have one comment:

After discussing this with a few other people, we decided that stacking stuns would be broken for now. So, could you make it so that if a stun is already in-place, the time isn't reset.

Basically:
```
if (stun == null) {
    // Add new stun to the entity.
    stun = new StunComponent();
    entity.addComponent(stun);
    // Add rest of code here...
}
```

Once that's done, I'll accept your PR. Great job overall.

**Comment by iojw** [comment]
I've committed the changes you mentioned.

**Comment by xrtariq2594** [comment]
Good work @iojw!

**Comment by iojw** [comment]
Thanks! 😄

**Pull request merged**
